services:
- docker

language: python
python:
  - "3.6"

install:
  - pip install pipenv pew
  - pipenv install --dev
  - pipenv shell
  - pip install -e .

script:
  - coverage run --source dockerpath -m py.test

after_script:
  - pip install --quiet coveralls && coveralls
